/* Conectado como usuário system */

-- Altera o container para o PDBORCL21
ALTER SESSION SET CONTAINER = PDBORCL21;

-- Cria o tablespace TBS_SOURCE
CREATE TABLESPACE tbs_source 
    DATAFILE '/u01/app/oracle/oradata/ORCL21/pdborcl21/TBS_SOURCE.dbf'
    SIZE 1M
    AUTOEXTEND ON NEXT 10M
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

-- Cria o usuário source
CREATE USER source IDENTIFIED BY source001 DEFAULT TABLESPACE tbs_source;
GRANT CONNECT, RESOURCE TO source;
GRANT UNLIMITED TABLESPACE TO source;

-- Cria a tablespace TBS_STAGE
CREATE TABLESPACE tbs_stage
    DATAFILE '/u01/app/oracle/oradata/ORCL21/pdborcl21/TBS_STAGE.dbf'
    SIZE 1M 
    AUTOEXTEND ON NEXT 10M 
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

-- Cria o usuário starea
CREATE USER starea IDENTIFIED BY starea001 DEFAULT TABLESPACE tbs_stage;
GRANT CONNECT, RESOURCE TO starea;
GRANT UNLIMITED TABLESPACE TO starea;

-- Cria a tablespace TBS_DW
CREATE TABLESPACE tbs_dw
    DATAFILE '/u01/app/oracle/oradata/ORCL21/pdborcl21/TBS_DW.dbf'
    SIZE 1M 
    AUTOEXTEND ON NEXT 10M
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

-- Cria o usuário dw
CREATE USER dw IDENTIFIED BY dw001 DEFAULT TABLESPACE tbs_dw;
GRANT CONNECT, RESOURCE TO dw;
GRANT UNLIMITED TABLESPACE TO dw;